# Generated by Django 5.0.4 on 2024-04-11 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="date_conclusion",
            field=models.DateTimeField(),
        ),
    ]
