# Generated by Django 5.0.4 on 2024-04-15 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdvertisingCompany",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField(blank=True, max_length=300)),
                ("promotion", models.CharField(max_length=50)),
                ("budget", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "services",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="services.service",
                    ),
                ),
            ],
            options={
                "verbose_name": "Advertising company",
                "verbose_name_plural": "Advertising companies",
                "ordering": ("id", "name"),
            },
        ),
    ]
