# Generated by Django 5.0.4 on 2024-04-10 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("advertising_companies", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advertisingcompany",
            name="name",
            field=models.CharField(max_length=50),
        ),
    ]
