# Generated by Django 5.0.4 on 2024-04-14 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("advertising_companies", "0002_alter_advertisingcompany_budget_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advertisingcompany",
            name="promotion",
            field=models.CharField(max_length=50),
        ),
    ]
