# Generated by Django 5.0.4 on 2024-04-10 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("advertising_companies", "0002_alter_advertisingcompany_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advertisingcompany",
            name="budget",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
