# Generated by Django 5.0.4 on 2024-04-10 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("advertising_companies", "0004_alter_advertisingcompany_budget_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="advertisingcompany",
            options={
                "ordering": ("id",),
                "verbose_name": "Advertising company",
                "verbose_name_plural": "Advertising companies",
            },
        ),
    ]
