# Generated by Django 5.0.4 on 2024-04-10 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("advertising_companies", "0005_alter_advertisingcompany_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="advertisingcompany",
            options={
                "ordering": ("id", "name"),
                "verbose_name": "Advertising company",
                "verbose_name_plural": "Advertising companies",
            },
        ),
    ]
