# Generated by Django 5.0.4 on 2024-04-10 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("advertising_companies", "0006_alter_advertisingcompany_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advertisingcompany",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
