# Generated by Django 5.0.4 on 2024-04-15 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("advertising_companies", "0001_initial"),
        ("contracts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("phone", models.CharField(max_length=10)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("active", models.BooleanField(default=False)),
                (
                    "advertising_company",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="advertising_companies.advertisingcompany",
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contracts.contract",
                    ),
                ),
            ],
            options={
                "verbose_name": "Potential client",
                "verbose_name_plural": "Potential clients",
                "ordering": ("id", "name"),
            },
        ),
    ]
