# Generated by Django 5.0.4 on 2024-04-11 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="active",
            field=models.BooleanField(default=False),
        ),
    ]
