# Generated by Django 5.0.4 on 2024-04-14 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0003_alter_client_email"),
        ("contracts", "0002_alter_contract_date_conclusion"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="contract",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contracts.contract",
            ),
        ),
    ]
