# Generated by Django 5.0.4 on 2024-04-10 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="service",
            options={
                "ordering": ("id",),
                "verbose_name": "Service",
                "verbose_name_plural": "Services",
            },
        ),
    ]
