# Generated by Django 5.0.4 on 2024-04-10 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0002_alter_service_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="service",
            options={
                "ordering": ("id", "name"),
                "verbose_name": "Service",
                "verbose_name_plural": "Services",
            },
        ),
    ]
