# Generated by Django 5.0.4 on 2024-04-10 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0003_alter_service_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="name",
            field=models.TextField(max_length=50, unique=True),
        ),
    ]
